### ISSUE TITLE
How this compares with arc4random?

### ISSUE THREAD

**Issue by ctarbide** [LoupVaillant/Monocypher-RNG#1]
Hi, I really like arc4random (1), is there any advantage in this new design of yours? Or any serious disadvantages in arc4random? I am just curious, thanks for sharing.

- 1: https://github.com/libressl-portable/openbsd/blob/master/src/lib/libc/crypt/arc4random.c

--ctarbide

EDIT: add arc4random implementation reference link from openbsd

**Comment by LoupVaillant** [comment]
Hi,

Actually, arc4random(3) and what I do here have very different use cases.

* arc4random(3) is a *system* RNG, that you can use safely without asking any question, *if* it is available on your system. If it’s not, you can usually re-implement it by using whatever system call you have available on your OS.
* Monocypher-RNG *user space* RNG with no dependencies (save Monocypher, which *really has* no dependencies). That makes it extremely portable, but the flip side is that’s it’s  a freaking footgun: it’s not thread safe, it’s not _fork_ safe, and basically it’s very easy to catastrophically misuse.
 
My advice: Monocypher-RNG, like any userspace RNG, should only be used as an _absolute last resort_. If you can use arc4random(3), use it. If you have another system RNG, implement arc4random(3) on top of it. If your RNG has limitations, get around them: retry as often as you need to, don’t hesitate to panic upon unrecoverable errors, and request at most 32 bytes at a time (use Chacha20 to expand those bytes into a stream of the required length). If you don’t have an RNG *at all*, then you can consider a user space RNG, but then you need to think hard about how you’re going to seed it.

Now, users pace RNGs do have one advantage over system RNG: once seeded, if used correctly, they cannot fail. That means you can request 32 random bytes when you initialise your program, and if that step succeeds, your RNG will never ever be a source of failure or crash. That is, if you use it correctly: you need to think about thread safety and fork safety: you need to spawn a separate RNG state for each thread, *times the number of forks*. It can be done, but personally I wouldn’t risk it except for simple programs like a single threaded batch program, or low stakes, such as a video game’s gameplay RNG.

Now there’s a really big advantage to user space RNG, that often apply to video games, but can be nice for simulations as well: it’s deterministic. If you remember the seed, you can re-generate the entire random stream, which can help reproduce exactly what happened on the first run. This is excellent for debugging (just replay the input logs), or if you want a replay system in your game.

---

If we’re talking about internal design, well… the biggest advantage of Monocypher-RNG is that it’s extremely short, and has no dependency besides Monocypher. Though when you look at it, arc4random(3) isn’t that big either, and given its role as a system RNG, its dependencies don’t look unjustified.

**Comment by ctarbide** [comment]
Thank you, learned a lot from your answer. Closing the issue, best regards.
--ctarbide
